### PR TITLE
processed with latest autocrop

### PR DESCRIPTION
**Pull request by AndreyKozlov1984**
@dankohn please review those changes, one file, `artwork/other/illustrations/ashley-mcnamara/kubectl/kubectl.svg` has an embedded png image and it was not processed.

### CODE REVIEW

**Comment by AndreyKozlov1984** [comment]
I've attached the diff, 
[autocrop-compare.html.pdf](https://github.com/cncf/artwork/files/3879753/autocrop-compare.html.pdf)

**Comment by dankohn** [comment]
Logo on page 130 is busted.

More generally, can you please change the boxes starting on page 1 to show the top and bottom borders of the processed logo. They should very rarely be square.

**Comment by AndreyKozlov1984** [comment]
[autocrop-compare.html.pdf](https://github.com/cncf/artwork/files/3906249/autocrop-compare.html.pdf)
I'm adding a latest pdf to compare.

**Comment by AndreyKozlov1984** [comment]
The image is still busted, though

**Comment by AndreyKozlov1984** [comment]
That busted image is a result of an SVGO option,  convertPathData, it failed on this svg with a globus. I can make this transform optional.

**Comment by dankohn** [comment]
Do you want to disable it for now and open an issue with SVGO upstream?

If you check if the generated PNG is different it will add a delay to the rendering of all images, won't it? Is that worth it to avoid bugs?

**Comment by AndreyKozlov1984** [comment]
We already do this for another risky transformation, thus an idea is to join all risky transformations together. I think if we start disabling the most effective transformation, which have a 0.1% failure rate, we will skip most advantages of an svg compression from svgo.

**Comment by dankohn** [comment]
I'm fine with adding a test. But, I'd like a report on all risky transformations so that we can open issues upstream.

**Comment by AndreyKozlov1984** [comment]
Ok, I'll check how I can report all examples of risky transformations to the generated compare.html file

**Comment by dankohn** [comment]
Since SVGO is mainly run on Netlify, that won't help, will it? Want to just do a special Slack message if you're on Netlify that calls out to each of us.

**Comment by AndreyKozlov1984** [comment]
Now it looks good, please check an attached pdf file
[autocrop-compare.html.pdf](https://github.com/cncf/artwork/files/3919106/autocrop-compare.html.pdf)

**Pull request merged**
