### PR TITLE
Adding Konveyor project artwork

### PR DESCRIPTION
**Pull request by savitharaghunathan**
Ref: https://github.com/cncf/toc/issues/880
Signed-off-by: Savitha Raghunathan <sraghuna@redhat.com>

### CODE REVIEW

**Comment by lukaszgryglicki** [comment]
For devstats I need a full set of logos, or at least `white` and `color` (as other projects do) - this one only adds `stacked`

You provided: `projects/konveyor/stacked/konveyor-stacked-color.svg|png`, while we need:
- `projects/konveyor/icon/[type]/konveyor-icon-[type].[ext]`.
Where `[type]` should be: white, color, black and `[ext]` should be png, svg - this gives 3x2 = 6 files needed.

**Comment by savitharaghunathan** [comment]
Hi @lukaszgryglicki, We have a ticket open with CNCF servicedesk to assist us with the creation of various other format for the logo. As a part of that, we were asked to submit what we have for the logo to the repo. @JonathanR19 Can you add the ticket id?

**Comment by lukaszgryglicki** [comment]
OK then, can you just update paths to match what I've suggested? I would approve then, so path would be:
`projects/konveyor/stacked/konveyor-stacked-color.svg|png` -> `projects/konveyor/icon/stacked/konveyor-icon-stacked.png|svg` or `projects/konveyor/icon/color/konveyor-icon-color.png|svg`
Not sure if last part in name shoudl be stacked or color - your path uses both - I'm not sure what's the difference between stacked and color but please choose one.

**Comment by savitharaghunathan** [comment]
@lukaszgryglicki updated the paths and name of the files. Please take a look.

**Review by lukaszgryglicki — APPROVED** [review]
/lgtm

**Comment by JonathanR19** [comment]
This is the service desk ticker:
https://cncfservicedesk.atlassian.net/servicedesk/customer/portal/1/CNCFSD-1387

**Pull request merged**
