### PR TITLE
add opcr project artwork

### PR DESCRIPTION
**Pull request by ogazitt**
Signed-off-by: Omri Gazitt <ogazitt@gmail.com>

Add Open Policy Containers (OPCR) project artwork.

### CODE REVIEW

**Comment by lukaszgryglicki** [comment]
Hi, can you update the PR so the paths are in standarized form, liek for example: https://github.com/cncf/artwork/tree/master/projects/crossplane

So that would be something like:
- `projects/opcr/icon/color/opcr-icon-color.svg`.
- `projects/opcr/icon/color/opcr-icon-color.png`.

**Comment by caniszczyk** [comment]
cc: @ogazitt to do the updates before merging in

**Comment by ogazitt** [comment]
> Hi, can you update the PR so the paths are in standarized form, liek for example: https://github.com/cncf/artwork/tree/master/projects/crossplane
> 
> So that would be something like:
> 
> * `projects/opcr/icon/color/opcr-icon-color.svg`.
> * `projects/opcr/icon/color/opcr-icon-color.png`.

Happy to do this, but since we have color logos with light and dark type, we modeled our directory structure on containerssh - https://github.com/cncf/artwork/blob/master/examples/sandbox.md#containerssh-logos

To apply the spirit of your suggestion, I propose the following:

 * `projects/opcr/icon/color/opcr-icon-color.svg`
 * `projects/opcr/icon/color/opcr-icon-color.png`
 * `projects/opcr/horizontal/color/opcr-horizontal-color.svg`
 * `projects/opcr/horizontal/color/opcr-horizontal-color.png`
 * `projects/opcr/horizontal/color/opcr-horizontal-color-dark.svg`
 * `projects/opcr/horizontal/color/opcr-horizontal-color-dark.png`
 * `projects/opcr/stacked/color/opcr-stacked-color.svg`
 * `projects/opcr/stacked/color/opcr-stacked-color.png`
 * `projects/opcr/stacked/color/opcr-stacked-color-dark.svg`
 * `projects/opcr/stacked/color/opcr-stacked-color-dark.png`

**Comment by ogazitt** [comment]
@lukaszgryglicki 

Let me know if this works for you:

```
ogazitt@Omris-MacBook-Pro:~/src/cncf/cncf-artwork/projects/opcr % tree
.
├── horizontal
│   └── color
│       ├── opcr-horizontal-color-dark.png
│       ├── opcr-horizontal-color-dark.svg
│       ├── opcr-horizontal-color.png
│       └── opcr-horizontal-color.svg
├── icon
│   └── color
│       ├── opcr-icon-color.png
│       └── opcr-icon-color.svg
└── stacked
    └── color
        ├── opcr-stacked-color-dark.png
        ├── opcr-stacked-color-dark.svg
        ├── opcr-stacked-color.png
        └── opcr-stacked-color.svg

6 directories, 10 files
```

**Comment by lukaszgryglicki** [comment]
Yep that will work for me. If you don't have some variant, just skip it, but please follow the directory structure I suggested

**Review by lukaszgryglicki — APPROVED** [review]
/lgtm once updated to reflect last two posts

**Pull request merged**
