### PR TITLE
tikv: batch update TiKV logo and icon to the latest

### PR DESCRIPTION
**Pull request by dcalvin**
Updated the TiKV logos and icons to the latest color scheme, and use horizontal icons instead of stack ones.

### CODE REVIEW

**Comment by dcalvin** [comment]
@lucperkins @alexcontini  Please take a look and help merge this PR if it looks good. Thanks.

**Comment by Hoverbear** [comment]
I see some odd borders here:

image

Could you fix this?

**Comment by Hoverbear** [comment]
I stand corrected, this might be a github bug: 
image

**Comment by dankohn** [comment]
It's a GitHub bug in their SVG viewer. Go back and forth between rich text and diff mode and it will eventually display correctly.

**Comment by dcalvin** [comment]
> It's a GitHub bug in their SVG viewer. Go back and forth between rich text and diff mode and it will eventually display correctly.

Hi @dankohn I see you close this PR. What should I do to get it merged, since we have updated our logos?

**Comment by dankohn** [comment]
Sorry about that. Could you please adjust the icon images to be square.

**Comment by dcalvin** [comment]
> Sorry about that. Could you please adjust the icon images to be square.

The icon images are already square (with the same width and height of 380 if you look inside) already square as you mentioned above - it's a Github SVG viewer bug. I switched back and forth between rich text and diff mode and the abnormal bound is gone.

**Comment by dankohn** [comment]
@alexcontini Could you please confirm that this looks good and, in particular, that the icon SVGs and PNGs are both square.

**Comment by dcalvin** [comment]
Thanks @dankohn and @alexcontini 
Could you please also confirm where I should update the icons on https://www.cncf.io/, for example, the TiKV icon below is still the old stacked style. 
image
We want the icons and logos to be what I updated in the PR. Thank you.

**Comment by dankohn** [comment]
@taylorwaggoner will fix it when she's back Monday. Thanks.

**Comment by dcalvin** [comment]
> @taylorwaggoner will fix it when she's back Monday. Thanks.

Sounds good. Thanks.

**Comment by taylorwaggoner** [comment]
I've updated the TiKV logo on cncf.io's homepage and projects page to be the horizontal version in the new color scheme.  Thanks!

**Pull request merged**
