### PR TITLE
Rename Prometheus logo to mention correct color

### PR DESCRIPTION
**Pull request by juliusv**
Fixes https://github.com/cncf/artwork/issues/9

### CODE REVIEW

**Comment by dankohn** [comment]
@juliusv We just refactored. Could you please confirm that the prometheus directory looks correct to you. https://github.com/cncf/artwork/tree/master/prometheus

**Comment by juliusv** [comment]
@dankohn Hmm, all the logos have text ("Prometheus") now, whereas before we had only the logo. I think the new text ones are mostly fine, but it would be good to keep the logo-only variants as well (old ones visible in this commit: https://github.com/cncf/artwork/tree/d9ad29465e19eff681d36cb9accbfb23621994b8/prometheus).

For the new SVG one, the cropping is a bit awkward: the horizontal logo+text is in the middle, but it's embedded in a large, otherwise empty and vertical (portrait mode) page.

**Comment by dankohn** [comment]
@juliusv We call text without words `icon`. They are here: https://github.com/cncf/artwork/tree/master/prometheus/icon

Do they look OK?

I agree that the SVG is problematic. @alexcontini could you please review the SVG and see if you can improve the cropping to be similar to the PNG. If the Prometheus one is wrong, could you please check all the other SVGs as well.

Thanks.

**Comment by juliusv** [comment]
@dankohn Whoops, I indeed missed the other directories. Those look fine, except for having the same cropping issues in the SVG version.

**Comment by dankohn** [comment]
Addressing in #17

**Pull request closed without merging**
