### PR TITLE
Add Microcks artwork

### PR DESCRIPTION
**Pull request by lbroudoux**
Adding artwork as required by cncf/toc#1096

### CODE REVIEW

**Comment by yada** [comment]
Can you merge and close this issue ?

**Comment by caniszczyk** [comment]
fix merge conflicts :)

**Review by yada — APPROVED** [review]

**Comment by yada** [comment]
Ok, will checkout master, pull and dig further ;-)

**Comment by lbroudoux** [comment]
Merged the latest changes from `master` and resolve conflicts.

**Review by lukaszgryglicki — APPROVED** [review]
/lgtm

**Comment by yada** [comment]
Fixed and ready to merge IMHO ;-)

**Pull request merged**
