### PR TITLE
Add Curiefense artwork

### PR DESCRIPTION
**Pull request by jdorfman**
Curiefense Logos + Examples

Helps to resolve cncf/toc#594

image

### CODE REVIEW

**Comment by caniszczyk** [comment]
@alexcontini can you clean this up?

**Comment by jdorfman** [comment]
@caniszczyk did I screw up? 😬

**Comment by alexcontini** [comment]
@caniszczyk  @jdorfman  just some small issues with the sandbox.md file, I wasn't sure how to actually edit the file in this PR, so I have created a new one with my changes - https://github.com/cncf/artwork/pull/214 , let me know if that doesn't work

**Comment by caniszczyk** [comment]
@jdorfman we can do it for you based on how we lay things out, no worries all done now!

https://github.com/cncf/artwork/pull/214

**Pull request closed without merging**
