### PR TITLE
Addition of the Kubestronaut logos

### PR DESCRIPTION
**Pull request by huats**
Addition of the various Kubestronaut logos.

### CODE REVIEW

**Review by cjyabraham — CHANGES_REQUESTED** [review]
I think it'd help to run the SVGs through [autocrop](https://autocrop.cncf.io/) which will crop the SVGs. And the PNGs should be cropped too to remove whitespace. Then you could also add link on [the main README file](https://github.com/cncf/artwork) to link to these logos.

**Comment by huats** [comment]
I think I have address your concerns @cjyabraham. Thanks for your new review

**Comment by cjyabraham** [comment]
Some of the SVGs still have a lot of whitespace. Did you pass them all through the autocrop service?
Screenshot 2024-04-18 at 10 17 26 AM

**Comment by huats** [comment]
I did ! (I just redo it again) ! Maybe autocrop is not enough ?

**Comment by cjyabraham** [comment]
There's something weird going on, when I view your recent commit, it looks like this, which looks correct:

Screenshot 2024-04-19 at 8 26 57 AM


But when I view the [Files changed](https://github.com/cncf/artwork/pull/471/files) for this PR, I see the same SVG like this with a lot more whitespace above and below:
Screenshot 2024-04-19 at 8 27 10 AM

Maybe we should just merge and then see what happens??

**Review by cjyabraham — APPROVED** [review]

**Comment by cjyabraham** [comment]
Sure. I'll merge it in.

**Pull request merged**
