### PR TITLE
kube-logging -> logging-operator

### PR DESCRIPTION
**Pull request by ahma**
Revert to the project's original name kube-logging -> logging-operator 
more info here -> https://github.com/cncf/toc/issues/1171

### CODE REVIEW

**Review by pepov — APPROVED** [review]

**Comment by tarokkk** [comment]
Hi @amye!
We fixed the naming and the light/dark themes in this PR for the Logging Operator project. Can you please take a look, and merge if it looks good?

**Comment by pepov** [comment]
@lukaszgryglicki sorry for the direct ping, could you take a look and approve if possible?

**Review by lukaszgryglicki — APPROVED** [review]
/lgtm
I'm OK with this and I will adjust DevStats once this is merged, but I don't know reasons behind renaming and maybe there are other people who needs to ack this, so I'm approving but not merging.
cc @caniszczyk

**Comment by pepov** [comment]
thanks! @caniszczyk this PR is applying the same issue you already approved here: https://github.com/cncf/landscape/pull/3758

**Comment by pepov** [comment]
And just to summarize: the original submission used the project name `logging-operator` but the artwork and the landscape config accidentally used the organization name `kube-logging`.

The landscape config has been fixed and we would love to have the artworks fixed as well.

**Comment by pepov** [comment]
@Cmierly perhaps you could help us with this please, since you were the one helping us with the original [PR](https://github.com/cncf/toc/issues/1171), so that we can finally get this in?

**Comment by lukaszgryglicki** [comment]
I've went ahead and merged.

**Pull request merged**
