### PR TITLE
add artwork for Carvel

### PR DESCRIPTION
**Pull request by microwavables**
I'm not sure if we have to request new artwork to match everyone else's options but this is the only artwork we have for Carvel to handoff to CNCF. We don't have all black/white logos, for example, like the others. But, here's everything we do have!

Signed-off-by: Nanci Lancaster <nancil@vmware.com>

### CODE REVIEW

**Comment by microwavables** [comment]
weird, I did do the 'signed-off-by' but still saying the check failed...

**Comment by microwavables** [comment]
fixed commit message, should be good now!

**Comment by microwavables** [comment]
@caniszczyk @lukaszgryglicki is this accurate?

**Comment by lukaszgryglicki** [comment]
icon/color SVG file is missing IMHO.

**Comment by microwavables** [comment]
> icon/color SVG file is missing IMHO.

@lukaszgryglicki  We do not have one of those in our Carvel brand folder :( . The only icon we have is the one I added. We would have to have VMware's brand team create one.

**Comment by alexcontini27** [comment]
@microwavables  I have added all the versions of the logo to github - https://github.com/cncf/artwork/blob/master/examples/sandbox.md#carvel-logos - let me know if there are any problems!

**Pull request merged**
