### PR TITLE
update tag env and tag env cloud native sustainability week logos

### PR DESCRIPTION
**Pull request by leonardpahlke**
* move the tag-env icons from the 2024-icons folder to the tag-env-sustainability folder.
* tag-env-sustainability logos are now in horizontal, icon and stacked format available
* cloud native sustainability week icons moved from the 2024-icons folder to a new tag-env-cloud-native-sustainability-week folder

these changes move files around & deletes the old logos.

### CODE REVIEW

**Comment by leonardpahlke** [comment]
cc @nate-double-u

**Comment by leonardpahlke** [comment]
FYI @Ludovik95

**Comment by nate-double-u** [comment]
Just circling around back to this, is there anything you want me to look at here @leonardpahlke, or is it still WIP?

**Comment by leonardpahlke** [comment]
Will update the PR next week. Have set time aside for it. Thanks for the reminder Nate 🙏

**Pull request closed without merging**
