### PR TITLE
add telepresence and move cloudevents logos

### PR DESCRIPTION
**Pull request by alexcontini**

### CODE REVIEW

**Comment by dankohn** [comment]
I don't think the stacked or horizontal version of Telepresence make sense. Can we just do the same for both, and then the icon will be square.

**Comment by dankohn** [comment]
Cc @lukaszgryglicki

**Comment by lukaszgryglicki** [comment]
Thanks, will update icons tomorrow.

**Comment by lukaszgryglicki** [comment]
Devstats icons updated both test and prod servers.

**Pull request merged**
