### PR TITLE
add cdk8s logos

### PR DESCRIPTION
**Pull request by tabern**
cdk8s logos + logo examples
Helps to resolve https://github.com/cncf/toc/issues/556 and https://github.com/awslabs/cdk8s/issues/451

### CODE REVIEW

**Comment by amye** [comment]
@alexcontini: any issues in here?

**Comment by tabern** [comment]
@alexcontini any update on reviewing this?

**Comment by alexcontini** [comment]
@tabern @amye  sorry about that!

There were a couple conflicts in the sandbox.md file that I removed, but otherwise looks great and will merge now

**Comment by tabern** [comment]
Woohoo! 🎉 thank you.

**Comment by lukaszgryglicki** [comment]
Hi, the PR was merged, but cdk8s is not following the default naming convention, so I need to add special cases in DevStats artwork.

Maybe worth following the exact naming convention?:

Other projects are named like this: `projects/{projectname}/icon/color/{projectname}-icon-color.{svg|png}`.
While cdk8s is named like this: `projects/{projectname}/icon/{projectname}.icon.color.{svg|png}`.
It misses the "color" directory (and also "white", "black"), and then it uses "." separator instead of "-".

Can we update this to avoid creating special cases ?

**Comment by alexcontini** [comment]
@lukaszgryglicki makes sense, I have updated the naming and folder structure to match the rest and PR is here - https://github.com/cncf/artwork/pull/213

**Pull request merged**
