### PR TITLE
Propose improvements to Argo BW logo versions.

### PR DESCRIPTION
**Pull request by todaywasawesome**
This proposal is to update the black and white versions of the Argo logo. The BW versions of Argo are used very sparingly today. This proposed version is meant to add dimension to the bw versions of the logo and make them more viable. 

white-versions

black-versions

Co-authored-by: Carmelle Blech <carmelle.blech@codefresh.io>
Co-authored-by: Dan Garfield <dan@codefresh.io>
Signed-off-by: Dan Garfield <dan@codefresh.io>

### CODE REVIEW

**Comment by jessesuen** [comment]
While I think the logos look better, I believe black and white logos are limited to just the colors: black and white, probably to accommodate the printing limitations for which these logs are intended for. I could be wrong about this. 

Also, with the text size being reduced, it makes the logo inconsistent with the color versions, and I think they are intended to be exactly the same but with different colors.

**Comment by todaywasawesome** [comment]
@jessesuen that's a good point though OPA has grayscale so it don't know if it's a hard requirement. I'll find out. 

https://github.com/cncf/artwork/blob/master/projects/opa/horizontal/black/opa-horizontal-black.png

**Comment by todaywasawesome** [comment]
@jessesuen I contact CNCF and they said grayscale is fine. @amye says "Add your changes in as a grayscale filename and that should be fine!"

**Comment by amye** [comment]
To be more clear: leave B&W as is, add greyscale so that no one loses anything. :)

**Comment by todaywasawesome** [comment]
Feedback from Argo Marketing Committee
* Make Argo type same size to not change between versions of logo
* Add more definition in mouth so it's more clear, right now it's too close to the body color to look clearly differentiated

**Comment by nate-double-u** [comment]
Hi @todaywasawesome, I appreciate your work here, but as it's a year on and this is still a WIP, I'm going to close it as stale. Please feel free to open a new PR if you come back to this work in future.

**Comment by todaywasawesome** [comment]
Fair, I'll be back!

**Comment by nate-double-u** [comment]
> Fair, I'll be back!

Glad to hear it!

**Pull request closed without merging**
