### PR TITLE
Update: Kuadrant. Added missing icons

### PR DESCRIPTION
**Pull request by jasonmadigan**
Last one, I think (thanks for the patience).

### CODE REVIEW

**Review by nate-double-u — CHANGES_REQUESTED** [review]
I think we may need to double check the exapmles/sandbox.md page, [the page preview](https://github.com/jasonmadigan/artwork/blob/kuadrant-icons/examples/sandbox.md#kuadrant-logos) (your branch) looks like it still has broken links.

**Comment by jasonmadigan** [comment]
@nate-double-u should be all-set now

**Review by lukaszgryglicki — APPROVED** [review]
/lgtm

**Review by nate-double-u — APPROVED** [review]
Thanks for the updates!

**Pull request merged**
