### PR TITLE
Adding envoy-gateway logos

### PR DESCRIPTION
**Pull request by nate-double-u**
Adding  Envoy-Gateway logos as per https://github.com/envoyproxy/gateway/issues/2147 & [CNCFSD-2420](https://cncfservicedesk.atlassian.net/browse/CNCFSD-2420)

closes https://github.com/envoyproxy/gateway/issues/2147

### CODE REVIEW

**Comment by nate-double-u** [comment]
@MB-Designs, I notice that there are some files that are `.eps` rather than `.svg`. Could you provide `.svg` files to replace those, or is there a specific reason you chose the `.eps` format?

**Comment by MB-Designs** [comment]
> @MB-Designs, I notice that there are some files that are `.eps` rather than `.svg`. Could you provide `.svg` files to replace those, or is there a specific reason you chose the `.eps` format?

Sorry, I will check and resend the requested format.

**Comment by nate-double-u** [comment]
Thanks!

**Comment by MB-Designs** [comment]
@nate-double-u SVG logos attached. Please check it. 
[envoy-gateway-logo-final.zip](https://github.com/user-attachments/files/16988782/envoy-gateway-logo-final.zip)

**Comment by nate-double-u** [comment]
Hi @MB-Designs, thanks for the updated files, but the `.svg`s seem to be broken (you can see in the preview). I get errors like the following when I try to open them locally:
```
This page contains the following errors:

error on line 16 at column 58: Namespace prefix inkscape for connector-curvature on path is not defined
Below is a rendering of the page up to the first error.
```

**Comment by MB-Designs** [comment]
@nate-double-u Sorry again, I will check and send the updated logos.

**Comment by nate-double-u** [comment]
Thanks @MB-Designs, I appreciate the effort you've put into these 🙂

**Comment by MB-Designs** [comment]
@nate-double-u I have regenerated the logo package. Please check it and let me know.

[envoy-gateway-logo-final.zip](https://github.com/user-attachments/files/17001309/envoy-gateway-logo-final.zip)

**Comment by nate-double-u** [comment]
Looks good, thanks @MB-Designs!

**Comment by arkodg** [comment]
@nate-double-u can we also add them to[ this](https://github.com/cncf/artwork/blob/main/examples/graduated.md#envoy-logos) table to make it easier to find the logos

**Comment by nate-double-u** [comment]
You could add them to that table, or if you'd like you can create an Envoy Gateway table immediately after it. Both would be fine.

**Pull request merged**
