### PR TITLE
Adding tag environmental sustainability new logo

### PR DESCRIPTION
**Pull request by Ludovik95**
Fixed the TAG environmental sustainability logo by placing a correct world map and adjusting some optical alignments and balances. Available in both plain and “Cloud Native Sustainability Week” versions.

### CODE REVIEW

**Review by leonardpahlke — APPROVED** [review]
LGTM, Thank you so much @Ludovik95 !

**Comment by leonardpahlke** [comment]
(i cannot merge it) cc @krook @jeefy

**Comment by nate-double-u** [comment]
Do we need to keep the old logos? I'd like to suggest that we archive the old logos and put the new 2024 logos in the main folder in a place of prominence - this should also update any sites that link directly to these logos. (i.e., replace the old logos with the new corrected ones)

@leonardpahlke @Ludovik95

**Comment by leonardpahlke** [comment]
Not sure why we would need to keep the old logos, just in case they would be available in the commit history, right? But we can keep them ofc. It does not come with a cost, having the old logos, I guess. 

> this should also update any sites that link directly to these logos. (i.e., replace the old logos with the new corrected ones)

Thats a good point. We need to close / update this PR https://github.com/cncf/artwork/pull/481 which aims to fix the folder structure. 

@Ludovik95 if you have the time, feel free to rearrange the folder structure. Otherwise, i will find time to do it a bit later of the week.

**Pull request merged**
